# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(439, 540)
        MainWindow.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setMinimumSize(QtCore.QSize(70, 100))
        self.btn1.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn1.setFont(font)
        self.btn1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(103, 103, 103);")
        self.btn1.setObjectName("btn1")
        self.horizontalLayout_4.addWidget(self.btn1)
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setMinimumSize(QtCore.QSize(70, 100))
        self.btn2.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn2.setFont(font)
        self.btn2.setStyleSheet("background-color: rgb(103, 103, 103);\n"
"color: rgb(255, 255, 255);")
        self.btn2.setObjectName("btn2")
        self.horizontalLayout_4.addWidget(self.btn2)
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setMinimumSize(QtCore.QSize(70, 100))
        self.btn3.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn3.setFont(font)
        self.btn3.setStyleSheet("background-color: rgb(103, 103, 103);\n"
"color: rgb(255, 255, 255);")
        self.btn3.setObjectName("btn3")
        self.horizontalLayout_4.addWidget(self.btn3)
        self.btnplus = QtWidgets.QPushButton(self.centralwidget)
        self.btnplus.setMinimumSize(QtCore.QSize(70, 100))
        self.btnplus.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnplus.setFont(font)
        self.btnplus.setStyleSheet("background-color: rgb(103, 103, 103);\n"
"color: rgb(255, 255, 255);")
        self.btnplus.setObjectName("btnplus")
        self.horizontalLayout_4.addWidget(self.btnplus)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setMinimumSize(QtCore.QSize(70, 100))
        self.btn4.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn4.setFont(font)
        self.btn4.setStyleSheet("background-color: rgb(103, 103, 103);\n"
"color: rgb(255, 255, 255);")
        self.btn4.setObjectName("btn4")
        self.horizontalLayout_3.addWidget(self.btn4)
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setMinimumSize(QtCore.QSize(70, 100))
        self.btn5.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn5.setFont(font)
        self.btn5.setStyleSheet("background-color: rgb(103, 103, 103);\n"
"color: rgb(255, 255, 255);")
        self.btn5.setObjectName("btn5")
        self.horizontalLayout_3.addWidget(self.btn5)
        self.btn6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn6.setMinimumSize(QtCore.QSize(70, 100))
        self.btn6.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn6.setFont(font)
        self.btn6.setStyleSheet("background-color: rgb(103, 103, 103);\n"
"color: rgb(255, 255, 255);")
        self.btn6.setObjectName("btn6")
        self.horizontalLayout_3.addWidget(self.btn6)
        self.btnminus = QtWidgets.QPushButton(self.centralwidget)
        self.btnminus.setMinimumSize(QtCore.QSize(70, 100))
        self.btnminus.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnminus.setFont(font)
        self.btnminus.setStyleSheet("\n"
"background-color: rgb(103, 103, 103);\n"
"color: rgb(255, 255, 255);")
        self.btnminus.setObjectName("btnminus")
        self.horizontalLayout_3.addWidget(self.btnminus)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn7.setMinimumSize(QtCore.QSize(70, 100))
        self.btn7.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn7.setFont(font)
        self.btn7.setStyleSheet("background-color: rgb(103, 103, 103);\n"
"color: rgb(255, 255, 255);")
        self.btn7.setObjectName("btn7")
        self.horizontalLayout_2.addWidget(self.btn7)
        self.btn8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn8.setMinimumSize(QtCore.QSize(70, 100))
        self.btn8.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn8.setFont(font)
        self.btn8.setStyleSheet("background-color: rgb(103, 103, 103);\n"
"color: rgb(255, 255, 255);")
        self.btn8.setObjectName("btn8")
        self.horizontalLayout_2.addWidget(self.btn8)
        self.btn9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn9.setMinimumSize(QtCore.QSize(70, 100))
        self.btn9.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn9.setFont(font)
        self.btn9.setStyleSheet("background-color: rgb(103, 103, 103);\n"
"color: rgb(255, 255, 255);")
        self.btn9.setObjectName("btn9")
        self.horizontalLayout_2.addWidget(self.btn9)
        self.btnmul = QtWidgets.QPushButton(self.centralwidget)
        self.btnmul.setMinimumSize(QtCore.QSize(70, 100))
        self.btnmul.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnmul.setFont(font)
        self.btnmul.setStyleSheet("background-color: rgb(103, 103, 103);\n"
"color: rgb(255, 255, 255);")
        self.btnmul.setObjectName("btnmul")
        self.horizontalLayout_2.addWidget(self.btnmul)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnxlear = QtWidgets.QPushButton(self.centralwidget)
        self.btnxlear.setMinimumSize(QtCore.QSize(70, 100))
        self.btnxlear.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnxlear.setFont(font)
        self.btnxlear.setStyleSheet("background-color: rgb(103, 103, 103);\n"
"color: rgb(255, 255, 255);")
        self.btnxlear.setObjectName("btnxlear")
        self.horizontalLayout.addWidget(self.btnxlear)
        self.btn0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0.setMinimumSize(QtCore.QSize(70, 100))
        self.btn0.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn0.setFont(font)
        self.btn0.setStyleSheet("background-color: rgb(103, 103, 103);\n"
"color: rgb(255, 255, 255);")
        self.btn0.setObjectName("btn0")
        self.horizontalLayout.addWidget(self.btn0)
        self.btndiv = QtWidgets.QPushButton(self.centralwidget)
        self.btndiv.setMinimumSize(QtCore.QSize(70, 100))
        self.btndiv.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btndiv.setFont(font)
        self.btndiv.setStyleSheet("background-color: rgb(103, 103, 103);\n"
"color: rgb(255, 255, 255);")
        self.btndiv.setObjectName("btndiv")
        self.horizontalLayout.addWidget(self.btndiv)
        self.btnans = QtWidgets.QPushButton(self.centralwidget)
        self.btnans.setMinimumSize(QtCore.QSize(70, 100))
        self.btnans.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnans.setFont(font)
        self.btnans.setStyleSheet("background-color: rgb(103, 103, 103);\n"
"color: rgb(255, 255, 255);")
        self.btnans.setObjectName("btnans")
        self.horizontalLayout.addWidget(self.btnans)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btnplus.setText(_translate("MainWindow", "+"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btnminus.setText(_translate("MainWindow", "-"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btnmul.setText(_translate("MainWindow", "*"))
        self.btnxlear.setText(_translate("MainWindow", "С"))
        self.btn0.setText(_translate("MainWindow", "0"))
        self.btndiv.setText(_translate("MainWindow", "/"))
        self.btnans.setText(_translate("MainWindow", "="))

    def add_functions(self):
            self.btn0.clicked.connect(self.def_write0)
            self.btn1.clicked.connect(self.def_write1)
            self.btn2.clicked.connect(self.def_write2)
            self.btn3.clicked.connect(self.def_write3)
            self.btn4.clicked.connect(self.def_write4)
            self.btn5.clicked.connect(self.def_write5)
            self.btn6.clicked.connect(self.def_write6)
            self.btn7.clicked.connect(self.def_write7)
            self.btn8.clicked.connect(self.def_write8)
            self.btn9.clicked.connect(self.def_write9)
            self.btnxlear.clicked.connect(self.def_writexlear)
            self.btnplus.clicked.connect(self.def_writeplus)
            self.btnminus.clicked.connect(self.def_writeminus)
            self.btnmul.clicked.connect(self.def_writemul)
            self.btndiv.clicked.connect(self.def_writediv)
            self.btnans.clicked.connect(self.def_writeans)
    
    def def_write0(self):
            
    
    def def_write1(self):
            
    
    def def_write2(self):
           
    
    def def_write3(self):
            
   
    def def_write4(self):
            
    
    def def_write5(self):
            
    
    def def_write6(self):
            
   
    def def_write7(self):
           
    
    def def_write8(self):
            
   
    def def_write9(self):
          
   
    def def_writexlear(self):
           
    
    def def_writeplus(self):
            

    def def_writeminus(self):
           

    def def_writemul(self):
            

    def def_writediv(self):
         

    def def_writeans(self):
          
    


if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec())
